//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscaEmprego.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereco
    {
        public Endereco()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int Id { get; set; }
        public string Logradouro { get; set; }
        public string Complemento { get; set; }
        public int CEP { get; set; }
        public string Tipo { get; set; }
        public long Telefone { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
