//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscaEmprego.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo
    {
        public Tipo()
        {
            this.Vaga = new HashSet<Vaga>();
        }
    
        public int Id { get; set; }
        public string Tipo1 { get; set; }
    
        public virtual ICollection<Vaga> Vaga { get; set; }
    }
}
