//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscaEmprego.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaga
    {
        public Vaga()
        {
            this.Vaga_Perfil = new HashSet<Vaga_Perfil>();
            this.Vaga_Usuario = new HashSet<Vaga_Usuario>();
        }
    
        public int Id { get; set; }
        public int Empresa_Id { get; set; }
        public int Tipo_Id { get; set; }
        public string Descricao { get; set; }
        public decimal Salario { get; set; }
        public string Beneficios { get; set; }
        public bool Ativa { get; set; }
        public System.DateTime Data_Cadastro { get; set; }
        public Nullable<System.DateTime> Data_Preenchimento_Vaga { get; set; }
        public Nullable<System.DateTime> Data_Cancelamento { get; set; }
        public Nullable<System.DateTime> Data_Ativacao { get; set; }
    
        public virtual Tipo Tipo { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Vaga_Perfil> Vaga_Perfil { get; set; }
        public virtual ICollection<Vaga_Usuario> Vaga_Usuario { get; set; }
    }
}
