//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscaEmprego.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaga_Perfil
    {
        public int Vaga_Id { get; set; }
        public int Perfil_Id { get; set; }
    
        public virtual Vaga Vaga { get; set; }
    }
}
